### ISSUE TITLE
Feature Request: Clone Patches

### ISSUE THREAD

**Issue by dannyhanes** [mondada/kinobi#4]
I would LOVE to be able to clone a patch inside of a software title. For a lot of our software, the only thing that changes is version number. I would love to hit clone, update the version number and hit save and have things like Kill Application, Dependencies, Capabilities and Kill Applications be pre-populated.

**Comment by jaystokes** [comment]
Hi Danny,

Thanks for the feature request!

We have been looking into this. We decided that cloning a patch wasn't the best approach for a number of reasons. The main reason being that it was easier to introduce errors if the cloned patch wasn't properly reviewed before being enabled.

We do however want to make patch creation easier so the upcoming release of Kinobi will autofill many of the fields that you are currently populating manually during patch creation.

We feel that this strikes a good balance between making patch creation quicker and easier, and ensuring that it's more difficult to end up with errors in the data as you are explicitly confirming it.

Thanks,
Jay Stokes
Developer at Mondada

**Comment by dannyhanes** [comment]
@jaystokes I am good with that. 

I just got Kinobi up and running and I am going through trying to build out ALL of the patches there felt like a ton of extra clicks and a lot of copy and pasting. haha

**Comment by matviyko** [comment]
Expecting immortal efficiency from the ephemeral unknown is the eternal dance of automation; at least, for myself (in these last years of human/organic I.T.).

Might I recommend a template-based option within the patching workflow, replacing the aforementioned cloning request; where all respective parties benefit :)

**Example**:
https://marketplace.atlassian.com/apps/1211044/issue-templates-for-jira?hosting=cloud&tab=overview

**Comment by duncan-mccracken** [comment]
Addressed in 1.2 release
