### ISSUE TITLE
Database restore causes Kinobi v1.2 to return to license screen + user creation

### ISSUE THREAD

**Issue by frankfd** [mondada/kinobi#7]
Hi, 

Prior to deployment I tried restoring a DB, however, using the standalone version of Kinobi 1.2, restoring causes to go back to the license agreement, URL repo selection and user creation, without actually restoring. 

Thanks, 
F.

**Comment by duncan-mccracken** [comment]
Hi @frankfd ,

README.md has been updated with some brief instructions on the migration process from NetSUS to a standalone installation.

If this doesn't cover everything off, please feel free to ask for clarification in the #kinobi-dev channel on MacAdmins Slack.

~Duncan
